# .readthedocs.yaml
version: 2

build:
  os: "ubuntu-20.04"  # Specify the OS for the build environment
  tools:
    python: "3.8"  # Specify the Python version

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt  # Path to the requirements file

