# .readthedocs.yaml
version: 2

build:
  image: "latest"  # Specify the build image

sphinx:
  configuration: docs/conf.py

python:
  version: "3.8"  # Specify the Python version
  install:
    - requirements: docs/requirements.txt  # Path to the requirements file

